// TODO(owner): draft based on the app's current behavior. Review every statement and fill in the TODO placeholders before launch.

export interface LegalSection {
  heading: string
  paragraphs?: string[]
  list?: string[]
}

export interface LegalDocumentData {
  title: string
  effectiveDate: string
  sections: LegalSection[]
}

export const termsContent: LegalDocumentData = {
  title: 'Terms of Service',
  effectiveDate: '2026-10-03',
  sections: [
    {
      heading: '1. Acceptance of Terms',
      paragraphs: [
        'By accessing or using FitWise, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.',
      ],
    },
    {
      heading: '2. Description of Service',
      paragraphs: [
        'FitWise is a web application that creates personalized workout and nutrition plans using artificial intelligence, based on the user\'s body stats and goals. The application also provides fitness calculators and progress tracking tools.',
        'FitWise provides general fitness and nutrition guidance, not medical advice. Always consult a qualified healthcare professional before starting a new diet or exercise program, especially if you have injuries or health conditions.',
      ],
    },
    {
      heading: '3. User Accounts',
      paragraphs: [
        'Sign-up and sign-in are conducted through Google OAuth. We receive your name and email address from Google when you authenticate.',
        'You must be at least 13 years old to use FitWise. [TODO: confirm minimum age.]',
        'You are responsible for maintaining the security of your account and for all activities that occur under your account.',
      ],
    },
    {
      heading: '4. Acceptable Use',
      paragraphs: ['You agree not to:'],
      list: [
        'Use the service for any unlawful purpose',
        'Attempt to gain unauthorized access to any part of the service',
        'Use automated systems to access the service (scraping, bots)',
        'Attempt to bypass any rate limits or usage restrictions',
        'Interfere with or disrupt the service or servers',
      ],
    },
    {
      heading: '5. AI-Generated Content',
      paragraphs: [
        'FitWise uses artificial intelligence to generate workout and nutrition plans. AI-generated content may contain errors or inaccuracies.',
        'Plans are generated by AI and may contain mistakes. Use at your own risk.',
        'The AI assistant receives your profile and latest plan as context to provide personalized responses.',
      ],
    },
    {
      heading: '6. Data and Privacy',
      paragraphs: [
        'Your data is stored with our database and authentication provider, Supabase. We do not sell your personal data.',
        'Chat messages are not stored on our servers; the recent conversation is kept in your browser session until the tab is closed.',
        'For more information about how we handle your data, please review our Privacy Policy.',
      ],
    },
    {
      heading: '7. Service Availability',
      paragraphs: [
        'We strive to keep the service available but do not guarantee uninterrupted access. We may change, suspend, or discontinue the service at any time without notice.',
        'The service is provided "as is" without warranties of any kind, express or implied.',
      ],
    },
    {
      heading: '8. Limitation of Liability',
      paragraphs: [
        'To the fullest extent permitted by law, FitWise shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly.',
        '[TODO: governing law/jurisdiction.]',
      ],
    },
    {
      heading: '9. Changes to These Terms',
      paragraphs: [
        'We may update these Terms of Service from time to time. When we do, users will be asked to accept the updated version before continuing to use the service.',
        'Continued use of the service after changes constitutes acceptance of the new terms.',
      ],
    },
  ],
}
